# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

newtrap_one_cpp <- function(fdist_and_fprime, safecheck_arg, start, tol = 0.01, maxit = 50L) {
    .Call('_gcipdrtest_newtrap_one_cpp', PACKAGE = 'gcipdrtest', fdist_and_fprime, safecheck_arg, start, tol, maxit)
}

findzerocorr <- function(xell, x, test, rf_type) {
    .Call('_gcipdrtest_findzerocorr', PACKAGE = 'gcipdrtest', xell, x, test, rf_type)
}

